server:
  port: 8888
redis: 
  pool: 
    data: 
      session: 
        host: 192.168.1.101:7111,192.168.1.201:7112,192.168.1.202:7113
spring:
  datasource:
    jndi-name: JDBC
    name: mySpringBoot
    url: jdbc:oracle:thin:@192.168.1.101:1521:DFKDB
    username: isecmdb
    password: isecmdb
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    minActive: 1
    maxActive: 20
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  thymeleaf: 
    prefix: classpath:/views/
    #content-type: text/html
    #suffix: .html
    #mode: HTML5
    #encoding: UTF-8
    # set to false for hot refresh
    cache: false
  dubbo:
    registry:
      address: zookeeper://192.168.1.80:3181
      port: 12880
    application:
      name: dubbo_ecom_consumer
    protocol:
      name: dubbo
    scan: com.cn.thinkx.ecom
  redis: 
    cluster: 
      nodes: 192.168.1.101:7111,192.168.1.201:7112,192.168.1.202:7113,192.168.1.202:7114,192.168.1.101:7115,192.168.1.201:7116
      connection-timeout: 1000
      soTimeout: 3000
      max-attempts: 5
      password: 
      max-redirects: 2
    timeout: 3000
    pool: 
      max-total: 1024
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
      block-when-exhausted: true
      max-wait-millis: 3000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      minEvictableIdleTimeMillis: 60000
      timeBetweenEvictionRunsMillis: 60000
      numTestsPerEvictionRun: 1  
  activemq:
    broker-url: failover:(tcp://192.168.1.101:51511,tcp://192.168.1.201:51512,tcp://192.168.1.202:51513)?randomize=false
    user: admin
    password: admin
    pool:
      max-connections: 10
wecard:
  wechat:
    msg: wecard.activemq.send.wechat.msg.v1
  template: 
    msg:
      mcht:
        v1: wecard.wechat.mcht.collection.bill.template.msg.v1
myBatis:
  mapperLocations: classpath:mapper/*.xml
  configLocations: classpath:conf/mybatis-config.xml
  #typeAliasesPackage: com.cn.thinx.ecom_cms.test.domain
logging:
  config: classpath:conf/logback-ecom.xml
  
#海意通加密Key(收银台，退款，查询)
HYT_SIGN_KEY: YPEgSbuyRcoDV49yHzx4wS4ZeKHFVQA84Hv4IunjH10
#家乐宝加密Key(收银台，退款，查询)
JLB_SIGN_KEY: LEPp3reCNRsd0J9jBwOJ6rxgUjbab1hHqOKKi3bE03r
#自建商城加密Key(收银台，退款，查询)
MYESHOP_SIGN_KEY: YPEgSbuyRcoDV49yHzx4wS4ZeKHFVQA84Hv4IunjH10
#海豚通通兑加密Key(收银台，退款，查询)
HTTTD_SIGN_KEY: YPEgSbuyRcoDV49yHzx4wS4ZeKHFVQA84Hv4IunjH10
#话费充值加密Key(收银台，退款，查询)
HFCZ_SIGN_KEY: dFZpBwT8qklMTNiRkCc2piHlxX7r6GMy

#电商下单地址（家乐宝，海镱通，海豚通通兑，自建商城）
ECOM_UNIFIEDORDER_URL: http://ecm.tao-lue.com/trans/order/unifiedOrder
#电商通知返回地址（家乐宝，海镱通，海豚通通兑，自建商城）
ECOM_NOTIFY_URL: http://ecm.tao-lue.com/trans/order/ecomBackResult
#电商重定向地址（家乐宝，海镱通，海豚通通兑，自建商城）
ECOM_REDIRECT_URL: http://ecm.tao-lue.com/trans/order/ecomRedirectResult
#电商退款地址（家乐宝，海镱通，海豚通通兑，自建商城）
ECOM_REFUND_URL: http://cas.tao-lue.com/ecom-cash/trans/order/ecomOrderRefund

#知了企服加密Key(收银台)
HKB_SIGN_KEY: YPEgSbuyRcoDV49yHzx4wS4ZeKHFVQA84Hv4IunjH10
#知了企服收银台地址
HKB_CASH_URL: http://hkb.tao-lue.com/trans/order/unifiedOrder.html
#知了企服查单接口地址
HKB_SEARCH_URL: http://hkb.tao-lue.com/trans/order/transOrderQuery.html
#知了企服退款接口地址
HKB_REFUND_URL: http://hkb.tao-lue.com/trans/order/transOrderRefund.html

#嘉福京东加密Key(收银台)
JF_SIGN_KEY: kec437d5o3956d1023k20ec9w08a9d27
#电商平台消费交易接口地址（嘉福京东）
transOrder: http://192.168.1.80:8888/order/transOrder.html
#电商平台订单查询接口地址（嘉福京东）
searchOrder: http://192.168.1.80:8888/order/searchOrder.html
#电商平台交易撤销接口地址（嘉福京东）
refundOrder: http://192.168.1.80:8888/order/refundOrder.html
